### ISSUE TITLE
otns failed to detect node uart type

### ISSUE THREAD

**Issue by anying11** [openthread/ot-ns#115]
I want to try this on Ubuntu18.04,but such a problem came to me and I don't know how to figure it.Here is the report.

warn  2021-03-19 11:07:04.750 - grpcwebproxy exit unexpectedly: exit status 1, try restarting ...
panic	2021-03-19 11:07:23.063 - expect line timeout: ""
panic	2021-03-19 11:07:23.066 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:965
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				node.go:655
	            				node.go:739
	            				simulation.go:109
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1371
	Error:      	Should be true

panic: 2021-03-19 11:07:23.063 - expect line timeout: ""
	panic: 2021-03-19 11:07:23.066 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:965
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				node.go:655
	            				node.go:739
	            				simulation.go:109
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1371
	Error:      	Should be true

goroutine 10 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000147600, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x565
go.uber.org/zap.(*SugaredLogger).log(0xc0000b0168, 0xb06804, 0xc00002d0c8, 0x8, 0xc000207ea0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf(0xb05f91, 0x3, 0xc0002840d0, 0x1, 0x1)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x185
github.com/simonlingoogle/go-simplelogger.assertLogger.Errorf(...)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:199
github.com/stretchr/testify/assert.Fail(0xbc8000, 0x100cea8, 0xb0d9ec, 0xe, 0x0, 0x0, 0x0, 0x17)
	/root/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:262 +0x2fb
github.com/stretchr/testify/assert.True(0xbc8000, 0x100cea8, 0xc00020b600, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:657 +0xae
github.com/simonlingoogle/go-simplelogger.AssertTrue(...)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:227
github.com/openthread/ot-ns/simulation.(*Node).inputCommand(0xc00010ed80, 0xb06535, 0x4)
	/ss/otns/simulation/node.go:191 +0x6e
github.com/openthread/ot-ns/simulation.(*Node).Exit(0xc00010ed80, 0xc00007a1b0, 0xc00020b788)
	/ss/otns/simulation/node.go:165 +0x45
github.com/openthread/ot-ns/simulation.(*Simulation).Stop(0xc0000780e0)
	/ss/otns/simulation/simulation.go:162 +0xcd
panic(0xa1cfa0, 0xc000feff50)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000147600, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x565
go.uber.org/zap.(*SugaredLogger).log(0xc0000b0168, 0xb06804, 0xc000105220, 0x1d, 0xc000207d60, 0x2, 0x2, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf(0xb14bfb, 0x18, 0xc00020bc68, 0x1, 0x1)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x185
github.com/openthread/ot-ns/simulation.(*Node).expectLine(0xc00010ed80, 0xa1cfa0, 0xbba4f0, 0x2540be400, 0x0, 0xbc7600, 0xc000226db0)
	/ss/otns/simulation/node.go:655 +0xf4
github.com/openthread/ot-ns/simulation.(*Node).detectVirtualTimeUART(0xc00010ed80)
	/ss/otns/simulation/node.go:739 +0xe5
github.com/openthread/ot-ns/simulation.(*Simulation).AddNode(0xc0000780e0, 0xc0002ef180, 0xc00030e0c0, 0xc00030e100, 0xc00030e0c0)
	/ss/otns/simulation/simulation.go:109 +0x2eb
github.com/openthread/ot-ns/cli.(*CmdRunner).executeAddNode.func1(0xc0000780e0)
	/ss/otns/cli/CmdRunner.go:317 +0x45
github.com/openthread/ot-ns/cli.(*CmdRunner).postAsyncWait.func1()
	/ss/otns/cli/CmdRunner.go:266 +0x3a
github.com/openthread/ot-ns/dispatcher.(*Dispatcher).Run(0xc000302300)
	/ss/otns/dispatcher/dispatcher.go:232 +0x53c
github.com/openthread/ot-ns/simulation.(*Simulation).Run(0xc0000780e0)
	/ss/otns/simulation/simulation.go:136 +0x11d
created by github.com/openthread/ot-ns/otns_main.Main
	/ss/otns/otns_main/otns_main.go:174 +0x365

**Comment by simonlingoogle** [comment]
Hi anying11,

Seeing from the logs, there may be some ot-cli-ftd process that was not
properly terminated. You can make sure that there is no ot-cli-ftd running
before launching OTNS.
You may also want to make sure that the ports from 9000 to 9033 are not
occupied by other processes.

BTW, could you share your command for building OpenThread?

BRs,

Simon Lin | Software Engineer, Nest Shanghai | ***@***.*** | +86
13656630312

**Comment by anying11** [comment]
Well,actually I built openthread and otns in the "root" model.And I  followed  the "GUIDE.md" step by step.Then I found that it is very difficult to start a browser under "root".So I copied the "otns"、"otns-reply"、"otns-silk-proxy" to someplace in the ordinary user's path.After starting a browser,I can add a new router,but whenever I refresh the network,it comes the problem.Now I make sure that the ports from 9000 to 9033 are free and there is no  ot-cli-ftd running.That's all.Thanks for your further help.

**Comment by simonlingoogle** [comment]
> After starting a browser,I can add a new router

Is the router working? For example, can it become a Leader?

> whenever I refresh the network,it comes the problem

What do you mean by "refresh the network"?

--- 

BTW, I followed GUIDE.md with latest OTNS and OpenThread code and it works.

**Comment by anying11** [comment]
No,I can only add one router.Then whatever I do it comes the problem."refresh the network" means that the browser automatically refresh itself or I choose to click the "f5" button.

**Comment by simonlingoogle** [comment]
I haven't seen issue like this. But I suspect that this has something to do with readline. 

Could you try if any following can solve the issue:

- Change the OpenThread build command to : `make -f examples/Makefile-simulation OTNS=1 VIRTUAL_TIME_UART=1`. Make sure to clean the build before rebuilding.
- Install readline-dev library and rebuild OpenThread.

Looking forward to see the results.

**Comment by anying11** [comment]
It works!I rebuilt it and I used "make -f examples/Makefile-simulation OTNS=1 VIRTUAL_TIME_UART=1".Thank you very much!

**Comment by simonlingoogle** [comment]
> It works!I rebuilt it and I used "make -f examples/Makefile-simulation OTNS=1 VIRTUAL_TIME_UART=1".Thank you very much!

Great to hear that it works. Could you help verify if installing readline can resolve this issue? Thanks.

**Comment by anying11** [comment]
No problem!But I haven't done such things before.How can I help verify it?And help people to the end,can you give me some advice on understanding the otns?I also haven't met such a big program before.Please!

**Comment by anying11** [comment]
May I ask how can I install readline?

**Comment by simonlingoogle** [comment]
> May I ask how can I install readline?

Please refer to docs like https://askubuntu.com/questions/194523/how-do-i-install-gnu-readline

**Comment by anying11** [comment]
> > May I ask how can I install readline?
> 
> Please refer to docs like https://askubuntu.com/questions/194523/how-do-i-install-gnu-readline

**Comment by anying11** [comment]
Sir,I have already install readline but such problem has still happened.And I have already rebuilt openthread and otns.Please help me.

**Comment by anying11** [comment]
Sir,I have tried to solved the problem and I debugged it.I found that the  message going to be written through        *net.UDPC onn udpln ,was ok.But the dispatcher listening to the same udpln can't receiver the message.There mey be some problem of the port.I will let you known if I find more.

**Comment by anying11** [comment]
The circumstance now is that when I add a node in command "add fedx 78 y 89 " and etc like this,the dispatcher and simulation and visualization part is ok ,and a event about "eventTypeStatusPush" comes to the dispather from port 9001.Then the event about "add node","on ext addr change","set node rloc" are sent to web.These things are ok.But at the same time,the  node should detectvirtualtime,and the event is sent to port 9001 by the dispatcher.But nobody gives a reply. The child process  is mightly wrong.

**Comment by anying11** [comment]
Sir,no matter where you are,I need your help.

**Comment by anying11** [comment]
May be a script to test the ot-cli-ftd whether is ok or not is a good idea.

**Comment by anying11** [comment]
> The circumstance now is that when I add a node in command "add fedx 78 y 89 " and etc like this,the dispatcher and simulation and visualization part is ok ,and a event about "eventTypeStatusPush" comes to the dispather from port 9001.Then the event about "add_node:{node_id:1 x:202 y:795 radio_range:160}","on_ext_addr_change:{node_id:1 ext_addr:9978708881329677104}","set_node_rloc16:{node_id:1 rloc16:65534}" are sent to web.These things are ok.
> But at the same time,the node should detectvirtualtime,and the event is sent to port 9001 by the dispatcher.But nobody gives a reply. The child process is mightly wrong.Hope for your answer.
> 1 node 2 linereader scan.scan() return nothing but false.
> Adn the "[]byte p" in otOutFilter.Read() has length of 4096 but all of them are 0.I think this is a key to the problem.



> Sir,I have tried to solved the problem and I debugged it.I found that the message going to be written through *net.UDPC onn udpln was ok.But the dispatcher listening to the same udpln can't receive the message.There may be some problem of the port.I will let you known if I find more.
> Now I found that after a message from port "9001" sent to the node,the node.peeraddr is set to 9001.

**Comment by anying11** [comment]
Big brother ,help me please!Big brother ,help me please!Big brother ,help me please!

**Comment by anying11** [comment]
I tried to use a go program to take use of port 9001 in advance,and I run the otns.The interesting thing is the main progress still receive events of "ext_addr_change"and "node_rloc16" in which port is 9001.

**Comment by anying11** [comment]
Sir,I need your help.

**Comment by jwhui** [comment]
Closing stale issue.
