### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by anying11** [openthread/ot-ns#121]
I tried to change make changes to the code,but it went wrong.Then although I downloaded  the codes again ,it came to such problem ,which makes me  horrible.Here is the report.
  
warn  2021-04-24 19:12:59.077 - grpcwebproxy exit unexpectedly: exit status 1, try restarting ...
panic	2021-04-24 19:13:17.947 - expect line timeout: ""
panic	2021-04-24 19:13:17.948 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:965
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				node.go:655
	            				node.go:739
	            				simulation.go:109
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1371
	Error:      	Should be true

panic: 2021-04-24 19:13:17.947 - expect line timeout: ""
	panic: 2021-04-24 19:13:17.948 - 
	Error Trace:	simplelogger.go:227
	            				node.go:191
	            				node.go:165
	            				simulation.go:162
	            				panic.go:965
	            				entry.go:230
	            				sugar.go:234
	            				sugar.go:159
	            				simplelogger.go:139
	            				node.go:655
	            				node.go:739
	            				simulation.go:109
	            				CmdRunner.go:317
	            				CmdRunner.go:266
	            				dispatcher.go:232
	            				simulation.go:136
	            				asm_amd64.s:1371
	Error:      	Should be true

goroutine 37 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000af6580, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x565
go.uber.org/zap.(*SugaredLogger).log(0xc000010178, 0xb06804, 0xc000314990, 0x8, 0xc000256420, 0x2, 0x2, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf(0xb05f91, 0x3, 0xc000aed960, 0x1, 0x1)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x185
github.com/simonlingoogle/go-simplelogger.assertLogger.Errorf(...)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:199
github.com/stretchr/testify/assert.Fail(0xbc8000, 0x100cea8, 0xb0d9ec, 0xe, 0x0, 0x0, 0x0, 0x17)
	/root/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:262 +0x2fb
github.com/stretchr/testify/assert.True(0xbc8000, 0x100cea8, 0xc000ad1600, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/stretchr/testify@v1.6.1/assert/assertions.go:657 +0xae
github.com/simonlingoogle/go-simplelogger.AssertTrue(...)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:227
github.com/openthread/ot-ns/simulation.(*Node).inputCommand(0xc00015c900, 0xb06535, 0x4)
	/otns/simulation/node.go:191 +0x6e
github.com/openthread/ot-ns/simulation.(*Node).Exit(0xc00015c900, 0xc00009a1b0, 0xc000ad1788)
	/otns/simulation/node.go:165 +0x45
github.com/openthread/ot-ns/simulation.(*Simulation).Stop(0xc0000980e0)
	/otns/simulation/simulation.go:162 +0xcd
panic(0xa1cfa0, 0xc000aed7e0)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000af6580, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x565
go.uber.org/zap.(*SugaredLogger).log(0xc000010178, 0xb06804, 0xc000ac2240, 0x1d, 0xc000256300, 0x2, 0x2, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/simonlingoogle/go-simplelogger.Panicf(0xb14bfb, 0x18, 0xc000ad1c68, 0x1, 0x1)
	/root/go/pkg/mod/github.com/simonlingoogle/go-simplelogger@v0.0.0-20191122025812-962af3877d65/simplelogger.go:139 +0x185
github.com/openthread/ot-ns/simulation.(*Node).expectLine(0xc00015c900, 0xa1cfa0, 0xbba4f0, 0x2540be400, 0x0, 0xbc7600, 0xc0002cb860)
	/otns/simulation/node.go:655 +0xf4
github.com/openthread/ot-ns/simulation.(*Node).detectVirtualTimeUART(0xc00015c900)
	/otns/simulation/node.go:739 +0xe5
github.com/openthread/ot-ns/simulation.(*Simulation).AddNode(0xc0000980e0, 0xc00006ea00, 0xc000390120, 0xc000390100, 0xc000390120)
	/otns/simulation/simulation.go:109 +0x2eb
github.com/openthread/ot-ns/cli.(*CmdRunner).executeAddNode.func1(0xc0000980e0)
	/otns/cli/CmdRunner.go:317 +0x45
github.com/openthread/ot-ns/cli.(*CmdRunner).postAsyncWait.func1()
	/otns/cli/CmdRunner.go:266 +0x3a
github.com/openthread/ot-ns/dispatcher.(*Dispatcher).Run(0xc000382480)
	/otns/dispatcher/dispatcher.go:232 +0x53c
github.com/openthread/ot-ns/simulation.(*Simulation).Run(0xc0000980e0)
	/otns/simulation/simulation.go:136 +0x11d
created by github.com/openthread/ot-ns/otns_main.Main
	/otns/otns_main/otns_main.go:174 +0x365
Can you help me ?

**Comment by simonlingoogle** [comment]
@anying11 How do you build openthread?

You can try turn on `VIRTUAL_TIME_UART`:
- Use `VIRTUAL_TIME_UART=1` for Makefile
- Use `-DOT_SIMULATION_VIRTUAL_TIME_UART=ON` for cmake

Please let me know if it works, Thanks.

**Comment by anying11** [comment]
Sorry,it doesn't work.Actually in the last issue,I met the same question,and to turn on VIRTUAL_TIME_UART works.By the way,every time I build the openthread,otns_0.reply and current.pcap in output/simulation/bin is absent,which should be there in my memory.

**Comment by anying11** [comment]
Sir,I built it with makefile,and I need your help desperately for now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openthread/ot-ns"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/ot-ns] problem (#121)





 
@anying11 How do you build openthread?
 
You can try turn on VIRTUAL_TIME_UART:
  
Use VIRTUAL_TIME_UART=1 for Makefile
 
Use -DOT_SIMULATION_VIRTUAL_TIME_UART=ON for cmake
  
Please let me know if it works, Thanks.

**Comment by anying11** [comment]
Sorry,I closed last issue bu mistake.And I have already installed readline,but such problem still happened.And I rebuilt openthread and otns.

**Comment by anying11** [comment]
May I ask how can I try it with cmake?

**Comment by anying11** [comment]
Sir ,may I ask is there somebody concerned about my question?

**Comment by simonlingoogle** [comment]
> May I ask how can I try it with cmake?Sir,I notice that in the oepnthread issue ,the uart API has changed due to some reason.Does my problem have something to do with it ?

You can try build using cmake:

In the openthread directory:
```
mkdir -p build/otns
cd build/otns
cmake -GNinja ../.. -DOT_PLATFORM=simulation -DOT_OTNS=ON -DOT_SIMULATION_VIRTUAL_TIME=ON -DOT_SIMULATION_VIRTUAL_TIME_UART=ON -DOT_SIMULATION_MAX_NETWORK_SIZE=999
ninja
```

**Comment by anying11** [comment]
No,it reports the same problem.

**Comment by simonlingoogle** [comment]
> No,it reports the same problem.

You may want to make sure that the UDP ports like 9000, 9001, ... are not occupied by other programs.

```bash
netstat -na | grep 9001 | grep udp
```

You may also want to check if there are zombie process of ot-cli-ftd and otns that are not terminated:
```bash
ps aux | grep ot-cli-ftd
```

**Comment by anying11** [comment]
No,I tried them one by one and I  quite sure that these are ok.

**Comment by hong123123-xll** [comment]
It seems that I met the same problem,does this one be figured out?

**Comment by simonlingoogle** [comment]
> Such words are in the list of reports when I run "make -f examples/Makefile-simulation OTNS=1"

You can try `make -f examples/Makefile-simulation OTNS=1 VIRTUAL_TIME_UART=1` see if issue can be fixed.

**Comment by simonlingoogle** [comment]
> may I ask you to upload the ot-cli-ftd of yours and let me try if it works.

Which OS are you running OpenThread?

> When the progctx of the main progress send an event about uart to the child progress,it didn't receive anything.

Can you help verify if the ot-cli-ftd process is still running?

**Comment by anying11** [comment]
ubuntu 18.04.
I think ot-cli-ftd process isn't running  properly.Cause when I click on "router" or etc,I use "lsof -i：8900-9100 "to visualize the port.But nobody uses port:9001 and >9001.And no process named ot-cli-ftd.

**Comment by simonlingoogle** [comment]
> ubuntu 18.04.
> I think ot-cli-ftd process isn't running properly.Cause when I click on "router" or etc,I use "lsof -i：8900-9100 "to visualize the port.But nobody uses port:9001 and >9001.And no process named ot-cli-ftd.

That pretty strange.

- First, please make sure you are running OTNS in the directory containing `ot-cli-ftd`, or use `-ot-cli` argument with correct path to `ot-cli-ftd`.
- If `ot-cli-ftd` somehow crashed, you can turn coredumps on by `ulimit -c unlimited` to generate the core dump file.

**Comment by anying11** [comment]
I promise the ot-cli-ftd is here.And there is no core.* file generate.PS:I have learned the coredump.

**Comment by hong123123-xll** [comment]
> > Such words are in the list of reports when I run "make -f examples/Makefile-simulation OTNS=1"
> 
> You can try `make -f examples/Makefile-simulation OTNS=1 VIRTUAL_TIME_UART=1` see if issue can be fixe

I think I am in the same circumstance with anying11.

**Comment by anying11** [comment]
Big brother,I really need your help.

**Comment by hong123123-xll** [comment]
> Big brother,I really need your help.

Wow,why are you so anxious?

**Comment by anying11** [comment]
Big brother,I need your kindness!

**Comment by anying11** [comment]
Sir,I need your help.

**Comment by anying11** [comment]
Sir,I found the key to the problem!I run otns in root module then ot-cli-ftd can run ordinarily.Thank you very much

**Comment by simonlingoogle** [comment]
@anying11 Glad to hear that it's working again.

I suspect the problem was that you ran `otns` in root so it has created a `tmp` directory with root permissions, which would forbid you from running `ot-cli-ftd` without root permission. 
You can simply remove the `tmp` directory so that you can run otns without root permission.

**Comment by anying11** [comment]
That's right.And may I ask If I want to send some data between two nodes by openthread,which class should I read?
 Is that coapmessage in dispatcher?





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "openthread/ot-ns"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/ot-ns] problem (#121)





 
@anying11 Glad to hear that it's working again.
 
I suspect the problem was that you ran otns in root so it has created a tmp directory with root permissions, which would forbid you from running ot-cli-ftd without root permission.
 You can simply remove the tmp directory so that you can run otns without root permission.

**Comment by simonlingoogle** [comment]
> That's right.And may I ask If I want to send some data between two nodes by openthread,which class should I read? Is that coapmessage in dispatcher?


You can use ping command or coap command to send data between two nodes. It does not have much to do with OTNS:
- ping: https://github.com/openthread/openthread/blob/main/src/cli/README.md#ping-ipaddr-size-count-interval-hoplimit-timeout
- coap: https://github.com/openthread/openthread/blob/main/src/cli/README_COAP.md

**Comment by anying11** [comment]
Big brother ,I love you so much!

**Comment by anying11** [comment]
I noticed that in the dispatcher part,alivenodes are  set to sleep due to alarmevents,and when they have some task to do,they would be set to be alive.But how do you make sure that setsleeping func and setalive func won't make conflict?

**Comment by simonlingoogle** [comment]
I am not exactly clear what do you mean by `make conflict`.

Basically, when a node enters sleep state, it will send an alarm event to the dispatcher, allowing the dispatcher to wait it up at the right time.
Whenever the dispatcher sends any message to the node, it will mark the node as `live`. The dispatcher always wait for all nodes to enter `sleep` state before it runs to the next timestamp.

**Comment by anying11** [comment]
Actually I simulation the hardware using multithreading  of go,which would send message by dispatcher to the ot-cli-ftd.Now,the problem is that,when main progress of otns get alarmevent from node,the alivenodes is arranged to sleep.But ibecause of the go multithreading,the alivenodes is arranged to be alive.Could I shutdown the func setsleeping  like in read mode?Would there be any problem ?

**Comment by anying11** [comment]
It seems that setsleeping and setalive play an very important part in otns,so I tried another way to handle trace bu sync.Thanks for your answer.

**Comment by simonlingoogle** [comment]
> Actually I simulation the hardware using multithreading of go,which would send message by dispatcher to the ot-cli-ftd.Now,the problem is that,when main progress of otns get alarmevent from node,the alivenodes is arranged to sleep.But ibecause of the go multithreading,the alivenodes is arranged to be alive.Could I shutdown the func setsleeping like in read mode when the alarmevent received?Would there be any problem ?

The short answer is that dispather should never run in multithreading.

**Comment by jwhui** [comment]
Closing stale issue.
