### ISSUE TITLE
Unable to install otns

### ISSUE THREAD

**Issue by PercyJaiswal** [openthread/ot-ns#232]
Hello, I am following instructions provided on =>https://openthread.io/codelabs/openthread-network-simulator#1
and have reached till following step 
```
$ ./script/install-deps
grpcwebproxy installed: /usr/local/google/home/simonlin/go/bin/grpcwebproxy
```
But when I try to install otns using
./script/install

I get following log msgs on my terminal
#------------------------------------------------------------------------------
percy@percy-VirtualBox:~/otns$ ./script/install
running install
running bdist_egg
running egg_info
writing pyOTNS.egg-info/PKG-INFO
writing dependency_links to pyOTNS.egg-info/dependency_links.txt
writing requirements to pyOTNS.egg-info/requires.txt
writing top-level names to pyOTNS.egg-info/top_level.txt
reading manifest file 'pyOTNS.egg-info/SOURCES.txt'
writing manifest file 'pyOTNS.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/otns
copying build/lib/otns/errors.py -> build/bdist.linux-x86_64/egg/otns
creating build/bdist.linux-x86_64/egg/otns/proto
copying build/lib/otns/proto/visualize_grpc_pb2.py -> build/bdist.linux-x86_64/egg/otns/proto
copying build/lib/otns/proto/visualize_grpc_pb2_grpc.py -> build/bdist.linux-x86_64/egg/otns/proto
copying build/lib/otns/proto/__init__.py -> build/bdist.linux-x86_64/egg/otns/proto
creating build/bdist.linux-x86_64/egg/otns/cli
copying build/lib/otns/cli/OTNS.py -> build/bdist.linux-x86_64/egg/otns/cli
copying build/lib/otns/cli/errors.py -> build/bdist.linux-x86_64/egg/otns/cli
copying build/lib/otns/cli/__init__.py -> build/bdist.linux-x86_64/egg/otns/cli
copying build/lib/otns/__init__.py -> build/bdist.linux-x86_64/egg/otns
byte-compiling build/bdist.linux-x86_64/egg/otns/errors.py to errors.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/proto/visualize_grpc_pb2.py to visualize_grpc_pb2.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/proto/visualize_grpc_pb2_grpc.py to visualize_grpc_pb2_grpc.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/proto/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/cli/OTNS.py to OTNS.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/cli/errors.py to errors.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/cli/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/otns/__init__.py to __init__.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyOTNS.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyOTNS.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyOTNS.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyOTNS.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyOTNS.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/pyOTNS-0.0.0-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyOTNS-0.0.0-py3.8.egg
Removing /home/percy/.local/lib/python3.8/site-packages/pyOTNS-0.0.0-py3.8.egg
Copying pyOTNS-0.0.0-py3.8.egg to /home/percy/.local/lib/python3.8/site-packages
pyOTNS 0.0.0 is already the active version in easy-install.pth

Installed /home/percy/.local/lib/python3.8/site-packages/pyOTNS-0.0.0-py3.8.egg
Processing dependencies for pyOTNS==0.0.0
Searching for PyYAML==5.3.1
Best match: PyYAML 5.3.1
Adding PyYAML 5.3.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for pyOTNS==0.0.0
/home/percy/otns
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
otns installed: 
percy@percy-VirtualBox:~/otns$ 
#------------------------------------------------------------------------------------------------------------------
As you can see in the end it says "otns installed", but I don't think its getting installed coz when I type 'which otns', I don't get any response.

Can someone please help me out :(
Let me know if you need any additional info.

My installation of Go was successful as I am able to get 'go version go1.18 linux/amd64' response on typing 'go version' command.

Thanks in Advance!!

**Comment by simonlingoogle** [comment]
I think otns was installed at `$GOPATH/bin`. 
So, you need to add `$GOPATH/bin` to your `$PATH`.

Usually, you can find what $GOPATH is via running `go env GOPATH`

**Comment by PercyJaiswal** [comment]
Thanks for the response Simon, but the issue is still there.

a) on running `go env GOPATH` I get following response => /home/percy/go
b) When I go the above directory /home/percy/go, I don't see 'otns' binary, just grpcwebproxy
c) Added $GOPATH/bin to my PATH using command `export PATH=$PATH:/home/percy/go/bin`
d) Still otns is not getting detected and on running `which otns`, I don't get any response.

Hope I am providing enough details to provide a good picture of the issue, please let me know if I should try something else on my side.

Thanks in Advance!!

**Comment by simonlingoogle** [comment]
Maybe otns does not compile on Go1.18, which I believe was just released. 
Have you tried a lower go version?

**Comment by simonlingoogle** [comment]
> I just reinstalled OTNS yesterday, and it worked just fine. But I did not install the new GO yet. It's possible that this is @simonlingoogle found the issue here.

Thanks for info. 
We actually found that otns does **not** build successfully in golang 1.18 docker container. See https://github.com/openthread/ot-ns/pull/243 for details

**Comment by simonlingoogle** [comment]
Seems `go get` no longer does what it used to do. 

Quote from golang 1.18 Release Notes:
```
go get
go get no longer builds or installs packages in module-aware mode. go get is now dedicated to adjusting dependencies in go.mod. Effectively, the -d flag is always enabled. To install the latest version of an executable outside the context of the current module, use [go install example.com/cmd@latest](https://golang.org/ref/mod#go-install). Any [version query](https://golang.org/ref/mod#version-queries) may be used instead of latest. This form of go install was added in Go 1.16, so projects supporting older versions may need to provide install instructions for both go install and go get. go get now reports an error when used outside a module, since there is no go.mod file to update. In GOPATH mode (with GO111MODULE=off), go get still builds and installs packages, as before.
```

I am not sure of a perfect solution that work in both golang 1.18 and previous versions.
But for now, you can run  following commands to install otns:
```
./script/install
go install ./cmd/...
```
@PercyJaiswal

**Comment by jwhui** [comment]
Closing stale issue.
