### ISSUE TITLE
GRPC generated file not automatically handled in OTNS repo

### ISSUE THREAD

**Issue by Vinggui** [openthread/ot-ns#272]
I have been trying to submit a PR here in OTNS that is changing the file `/visualize/grpc/pb/visualize_grpc.proto`, but it is having some building errors. Then, I found out that `.gitignore` has [this line](https://github.com/openthread/ot-ns/blob/8b7655fe3802517088627e63d0f632f2460d700c/.gitignore#L37) `/visualize/grpc/pb/*.pb.go` which blocks the new generated file to be pushed. It is not a real problem, we just need to force-add that file, since this would avoid making all users to install and compile the proto package every time they install OTNS.

My issue is: should we have a GitHub Action to check if  `/visualize/grpc/pb/visualize_grpc.proto` was modified, automatically generate a new pb file, and merge into the repository?

**Comment by simonlingoogle** [comment]
Maybe we should remove `/visualize/grpc/pb/visualize_grpc.proto` from .gitignore. 

> My issue is: should we have a GitHub Action to check if /visualize/grpc/pb/visualize_grpc.proto was modified, automatically generate a new pb file, and merge into the repository?

I am not sure if workflow can change the pb file and merge to repository. 
But it's definitely doable to add a workflow to make sure the .pb.go is properly generated.

**Comment by Vinggui** [comment]
I agree, adding an exception to `/visualize/grpc/pb/visualize_grpc.pb.go` in .gitignore may be enough.

**Comment by jwhui** [comment]
Closing stale issue.
